import React from 'react';
import Providers from './provider';

import './global.css';

export const metadata = {
  title: 'Welcome to party-fun-box',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://www.youtube.com/iframe_api" defer />
      </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
